version: '3.9'
services:
  traefik:
    labels: 
      - traefik.enable=false
  backend:
    volumes:
      - ./vers/app:/app
    command: /start-reload.sh
    ports:
      - 8080:80
    labels: 
      - traefik.enable=false
  pgadmin:
    labels: 
      - traefik.enable=false
    ports:
      - 5050:5050
networks:
  traefik-public:
    external: false