version: '3.3'
services:

  backend:
    ports:
      - 80:80

  # grafana:
  #   ports:
  #     - 3000:3000

  # prometheus:
  #   ports: 
  #     - 9090:9090
  
  # statsd-exporter:
  #   ports:
  #     - 9123:9102
  #     - 8125:8125/udp

  # flower:
  #   ports:
  #     - "5555:5555"

  # webserver:
  #   ports:
  #     - "8080:8080"
            
      
networks:
  traefik-public:
    external: false
