version: "3.9"

services:
  backend:
    container_name: bocr
    env_file:
      - .env
    volumes:
      - ./:/app
    build:
      context: ./
      dockerfile: Dockerfile
    command: sh scripts/start-reload.sh
    ports:
      - 8080:80
    restart: always


  db:
    image: postgres:12
    container_name: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 5050:5050
volumes:
  app-db-data:
