apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bocr-dep
  name: bocr-dep
  namespace: nebo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bocr-dep
  template:
    metadata:
      labels:
        app: bocr-dep
    spec:
      containers:
        - args:
            - /start-reload.sh
          envFrom:
            - configMapRef:
                name: env
                optional: false
          image: registry.nebo.africa/bocr:latest
          imagePullPolicy: IfNotPresent
          name: bocr-dep
          resources: {}